import {
  ContextData,
  MarketData,
  Maturity,
  Security,
} from './optionMatrix.types';

const options_ggal_202210: Security[] = [
  {
    id: 'bm_MERV_GFGC12929O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC12929O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000129.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 129.29,
  },
  {
    id: 'bm_MERV_GFGV12929O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV12929O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000129.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 129.29,
  },
  {
    id: 'bm_MERV_GFGC132_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC132.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000132.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132,
  },
  {
    id: 'bm_MERV_GFGV132_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV132.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000132.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132,
  },
  {
    id: 'bm_MERV_GFGC13229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC13229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000132.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132.29,
  },
  {
    id: 'bm_MERV_GFGV13229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV13229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000132.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132.29,
  },
  {
    id: 'bm_MERV_GFGC135_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC135.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000135.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 135,
  },
  {
    id: 'bm_MERV_GFGV135_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV135.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000135.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 135,
  },
  {
    id: 'bm_MERV_GFGC13729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC13729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000137.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 137.29,
  },
  {
    id: 'bm_MERV_GFGV13729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV13729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000137.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 137.29,
  },
  {
    id: 'bm_MERV_GFGC140_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC140.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000140.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 140,
  },
  {
    id: 'bm_MERV_GFGV140_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV140.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000140.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 140,
  },
  {
    id: 'bm_MERV_GFGC14229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC14229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000142.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 142.29,
  },
  {
    id: 'bm_MERV_GFGV14229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV14229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000142.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 142.29,
  },
  {
    id: 'bm_MERV_GFGC145_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC145.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000145.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 145,
  },
  {
    id: 'bm_MERV_GFGV145_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV145.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000145.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 145,
  },
  {
    id: 'bm_MERV_GFGC14729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC14729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000147.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 147.29,
  },
  {
    id: 'bm_MERV_GFGV14729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV14729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000147.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 147.29,
  },
  {
    id: 'bm_MERV_GFGC150_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC150.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000150.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 150,
  },
  {
    id: 'bm_MERV_GFGV150_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV150.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000150.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 150,
  },
  {
    id: 'bm_MERV_GFGC15229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC15229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000152.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 152.29,
  },
  {
    id: 'bm_MERV_GFGV15229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV15229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000152.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 152.29,
  },
  {
    id: 'bm_MERV_GFGC155_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC155.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000155.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 155,
  },
  {
    id: 'bm_MERV_GFGV155_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV155.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000155.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 155,
  },
  {
    id: 'bm_MERV_GFGC15729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC15729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000157.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 157.29,
  },
  {
    id: 'bm_MERV_GFGV15729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV15729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000157.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 157.29,
  },
  {
    id: 'bm_MERV_GFGC160_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC160.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000160.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 160,
  },
  {
    id: 'bm_MERV_GFGV160_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV160.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000160.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 160,
  },
  {
    id: 'bm_MERV_GFGC16229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC16229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000162.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 162.29,
  },
  {
    id: 'bm_MERV_GFGV16229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV16229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000162.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 162.29,
  },
  {
    id: 'bm_MERV_GFGC165_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC165.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000165.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 165,
  },
  {
    id: 'bm_MERV_GFGV165_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV165.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000165.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 165,
  },
  {
    id: 'bm_MERV_GFGC16729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC16729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000167.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 167.29,
  },
  {
    id: 'bm_MERV_GFGV16729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV16729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000167.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 167.29,
  },
  {
    id: 'bm_MERV_GFGC170_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC170.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000170.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 170,
  },
  {
    id: 'bm_MERV_GFGV170_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV170.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000170.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 170,
  },
  {
    id: 'bm_MERV_GFGC17229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC17229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000172.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 172.29,
  },
  {
    id: 'bm_MERV_GFGV17229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV17229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000172.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 172.29,
  },
  {
    id: 'bm_MERV_GFGC175_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC175.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000175.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 175,
  },
  {
    id: 'bm_MERV_GFGV175_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV175.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000175.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 175,
  },
  {
    id: 'bm_MERV_GFGC17729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC17729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000177.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 177.29,
  },
  {
    id: 'bm_MERV_GFGV17729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV17729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000177.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 177.29,
  },
  {
    id: 'bm_MERV_GFGC17983O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC17983O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000179.8300:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 179.83,
  },
  {
    id: 'bm_MERV_GFGV17983O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV17983O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000179.8300:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 179.83,
  },
  {
    id: 'bm_MERV_GFGC180_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC180.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000180.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 180,
  },
  {
    id: 'bm_MERV_GFGV180_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV180.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000180.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 180,
  },
  {
    id: 'bm_MERV_GFGC18229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC18229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000182.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 182.29,
  },
  {
    id: 'bm_MERV_GFGV18229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV18229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000182.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 182.29,
  },
  {
    id: 'bm_MERV_GFGC18254O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC18254O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000182.5400:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 182.54,
  },
  {
    id: 'bm_MERV_GFGV18254O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV18254O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000182.5400:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 182.54,
  },
  {
    id: 'bm_MERV_GFGC185_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC185.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000185.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 185,
  },
  {
    id: 'bm_MERV_GFGV185_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV185.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000185.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 185,
  },
  {
    id: 'bm_MERV_GFGC190_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC190.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000190.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 190,
  },
  {
    id: 'bm_MERV_GFGV190_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV190.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000190.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 190,
  },
  {
    id: 'bm_MERV_GFGC19229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC19229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000192.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 192.29,
  },
  {
    id: 'bm_MERV_GFGV19229O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV19229O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000192.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 192.29,
  },
  {
    id: 'bm_MERV_GFGC195_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC195.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000195.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 195,
  },
  {
    id: 'bm_MERV_GFGV195_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV195.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000195.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 195,
  },
  {
    id: 'bm_MERV_GFGC19729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC19729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000197.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 197.29,
  },
  {
    id: 'bm_MERV_GFGV19729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV19729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000197.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 197.29,
  },
  {
    id: 'bm_MERV_GFGC200_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC200.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000200.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 200,
  },
  {
    id: 'bm_MERV_GFGV200_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV200.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000200.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 2,
    sizePrecision: 0,
    strikePrice: 200,
  },
  {
    id: 'bm_MERV_GFGC20729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC20729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000207.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 207.29,
  },
  {
    id: 'bm_MERV_GFGV20729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV20729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000207.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 207.29,
  },
  {
    id: 'bm_MERV_GFGC210_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC210.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000210.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 210,
  },
  {
    id: 'bm_MERV_GFGV210_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV210.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000210.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 210,
  },
  {
    id: 'bm_MERV_GFGC21729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC21729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000217.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 217.29,
  },
  {
    id: 'bm_MERV_GFGV21729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV21729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000217.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 217.29,
  },
  {
    id: 'bm_MERV_GFGC220_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC220.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000220.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 220,
  },
  {
    id: 'bm_MERV_GFGV220_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV220.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000220.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 220,
  },
  {
    id: 'bm_MERV_GFGC22729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC22729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000227.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 227.29,
  },
  {
    id: 'bm_MERV_GFGV22729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV22729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000227.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 227.29,
  },
  {
    id: 'bm_MERV_GFGC230_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC230.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000230.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 230,
  },
  {
    id: 'bm_MERV_GFGV230_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV230.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000230.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 230,
  },
  {
    id: 'bm_MERV_GFGC23729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC23729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000237.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 237.29,
  },
  {
    id: 'bm_MERV_GFGV23729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV23729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000237.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 237.29,
  },
  {
    id: 'bm_MERV_GFGC240_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC240.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000240.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 240,
  },
  {
    id: 'bm_MERV_GFGV240_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV240.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000240.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 240,
  },
  {
    id: 'bm_MERV_GFGC24729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC24729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000247.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 247.29,
  },
  {
    id: 'bm_MERV_GFGV24729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV24729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000247.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 247.29,
  },
  {
    id: 'bm_MERV_GFGC250_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC250.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000250.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 250,
  },
  {
    id: 'bm_MERV_GFGV250_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV250.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000250.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 250,
  },
  {
    id: 'bm_MERV_GFGC25729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC25729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000257.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 257.29,
  },
  {
    id: 'bm_MERV_GFGV25729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV25729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000257.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 257.29,
  },
  {
    id: 'bm_MERV_GFGC260_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC260.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000260.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 260,
  },
  {
    id: 'bm_MERV_GFGV260_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV260.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000260.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 260,
  },
  {
    id: 'bm_MERV_GFGC26729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC26729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000267.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 267.29,
  },
  {
    id: 'bm_MERV_GFGV26729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV26729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000267.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 267.29,
  },
  {
    id: 'bm_MERV_GFGC270_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC270.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000270.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 270,
  },
  {
    id: 'bm_MERV_GFGV270_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV270.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000270.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 270,
  },
  {
    id: 'bm_MERV_GFGC27729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC27729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000277.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 277.29,
  },
  {
    id: 'bm_MERV_GFGV27729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV27729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000277.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 277.29,
  },
  {
    id: 'bm_MERV_GFGC280_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC280.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000280.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 280,
  },
  {
    id: 'bm_MERV_GFGV280_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV280.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000280.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 280,
  },
  {
    id: 'bm_MERV_GFGC28729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC28729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000287.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 287.29,
  },
  {
    id: 'bm_MERV_GFGV28729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV28729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000287.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 287.29,
  },
  {
    id: 'bm_MERV_GFGC290_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC290.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000290.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 290,
  },
  {
    id: 'bm_MERV_GFGV290_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV290.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000290.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 290,
  },
  {
    id: 'bm_MERV_GFGC29729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC29729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000297.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 297.29,
  },
  {
    id: 'bm_MERV_GFGV29729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV29729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000297.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 297.29,
  },
  {
    id: 'bm_MERV_GFGC300_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC300.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000300.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 300,
  },
  {
    id: 'bm_MERV_GFGV300_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV300.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000300.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 300,
  },
  {
    id: 'bm_MERV_GFGC30729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC30729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000307.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 307.29,
  },
  {
    id: 'bm_MERV_GFGV30729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV30729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000307.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 307.29,
  },
  {
    id: 'bm_MERV_GFGC310_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC310.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000310.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 310,
  },
  {
    id: 'bm_MERV_GFGV310_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV310.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000310.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 310,
  },
  {
    id: 'bm_MERV_GFGC31729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC31729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000317.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 317.29,
  },
  {
    id: 'bm_MERV_GFGV31729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV31729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000317.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 317.29,
  },
  {
    id: 'bm_MERV_GFGC320_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC320.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000320.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 320,
  },
  {
    id: 'bm_MERV_GFGV320_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV320.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000320.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 320,
  },
  {
    id: 'bm_MERV_GFGC32729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC32729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000327.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 327.29,
  },
  {
    id: 'bm_MERV_GFGV32729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV32729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000327.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 327.29,
  },
  {
    id: 'bm_MERV_GFGC330_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC330.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000330.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 330,
  },
  {
    id: 'bm_MERV_GFGV330_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV330.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000330.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 330,
  },
  {
    id: 'bm_MERV_GFGC33729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC33729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000337.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 337.29,
  },
  {
    id: 'bm_MERV_GFGV33729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV33729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000337.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 337.29,
  },
  {
    id: 'bm_MERV_GFGC340_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC340.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000340.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 340,
  },
  {
    id: 'bm_MERV_GFGV340_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV340.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000340.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 340,
  },
  {
    id: 'bm_MERV_GFGC34729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC34729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000347.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 347.29,
  },
  {
    id: 'bm_MERV_GFGV34729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV34729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000347.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 347.29,
  },
  {
    id: 'bm_MERV_GFGC350_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC350.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000350.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 350,
  },
  {
    id: 'bm_MERV_GFGV350_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV350.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000350.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 350,
  },
  {
    id: 'bm_MERV_GFGC35729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC35729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000357.2900:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 357.29,
  },
  {
    id: 'bm_MERV_GFGV35729O_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV35729O (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000357.2900:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 357.29,
  },
  {
    id: 'bm_MERV_GFGC360_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGC360.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000360.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 360,
  },
  {
    id: 'bm_MERV_GFGV360_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'GFGV360.OC (24hs)',
    description: 'Grupo Financiero Galicia',
    sortCode: 'bm:GGAL:b:2022:10:000360.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_GGAL_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 360,
  },
];

const options_cepu_202210: Security[] = [
  {
    id: 'bm_MERV_CEPV64_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV64.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000064.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 64,
  },
  {
    id: 'bm_MERV_CEPV68_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV68.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000068.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 68,
  },
  {
    id: 'bm_MERV_CEPV72_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV72.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000072.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 72,
  },
  {
    id: 'bm_MERV_CEPV76_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV76.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000076.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 76,
  },
  {
    id: 'bm_MERV_CEPV80_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV80.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000080.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 80,
  },
  {
    id: 'bm_MERV_CEPV84_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV84.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000084.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 84,
  },
  {
    id: 'bm_MERV_CEPV92_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV92.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000092.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 92,
  },
  {
    id: 'bm_MERV_CEPV96_0OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV96.0OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000096.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 96,
  },
  {
    id: 'bm_MERV_CEPV100_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV100.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000100.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 100,
  },
  {
    id: 'bm_MERV_CEPV104_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV104.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000104.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 104,
  },
  {
    id: 'bm_MERV_CEPC108_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC108.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000108.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 108,
  },
  {
    id: 'bm_MERV_CEPV108_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV108.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000108.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 108,
  },
  {
    id: 'bm_MERV_CEPV120_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV120.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000120.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 120,
  },
  {
    id: 'bm_MERV_CEPV124_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV124.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000124.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 124,
  },
  {
    id: 'bm_MERV_CEPC128_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC128.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000128.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 128,
  },
  {
    id: 'bm_MERV_CEPV128_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV128.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000128.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 128,
  },
  {
    id: 'bm_MERV_CEPC132_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC132.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000132.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132,
  },
  {
    id: 'bm_MERV_CEPV132_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV132.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000132.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 132,
  },
  {
    id: 'bm_MERV_CEPC136_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC136.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000136.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 136,
  },
  {
    id: 'bm_MERV_CEPV136_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV136.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000136.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 136,
  },
  {
    id: 'bm_MERV_CEPC140_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC140.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000140.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 140,
  },
  {
    id: 'bm_MERV_CEPV140_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV140.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000140.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 140,
  },
  {
    id: 'bm_MERV_CEPC144_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPC144.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000144.0000:c',
    type: 'OPTION_CALL',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 144,
  },
  {
    id: 'bm_MERV_CEPV144_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CEPV144.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000144.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 144,
  },
  {
    id: 'bm_MERV_CREV170_OC_24hs',
    marketSegment: {
      id: 'bm_MERV',
      description: 'MERVAL',
      market: { id: 'bm', description: 'MERVAL' },
    },
    symbol: 'CREV170.OC (24hs)',
    description: 'Central Puerto',
    sortCode: 'bm:CEPU:b:2022:10:000170.0000:p',
    type: 'OPTION_PUT',
    isUnderlying: false,
    underlying: 'bm_MERV_CEPU_48hs',
    pricePrecision: 3,
    sizePrecision: 0,
    strikePrice: 170,
  },
];

const underlying_ggal: Security = {
  id: 'bm_MERV_GGAL_48hs',
  marketSegment: {
    id: 'bm_MERV',
    description: 'MERVAL',
    market: { id: 'bm', description: 'MERVAL' },
  },
  symbol: 'GGAL',
  description: 'Grupo Financiero Galicia',
  sortCode: 'bm:GGAL:a:48hs',
  type: 'STOCK',
  isUnderlying: true,
  underlying: 'bm_MERV_GGAL_48hs',
  pricePrecision: 2,
  sizePrecision: 0,
};

const underlying_cepu: Security = {
  id: 'bm_MERV_CEPU_48hs',
  marketSegment: {
    id: 'bm_MERV',
    description: 'MERVAL',
    market: { id: 'bm', description: 'MERVAL' },
  },
  symbol: 'CEPU',
  description: 'Central Puerto',
  sortCode: 'bm:CEPU:a:48hs',
  type: 'STOCK',
  isUnderlying: true,
  underlying: 'bm_MERV_CEPU_48hs',
  pricePrecision: 2,
  sizePrecision: 0,
};

const underlyings: Security[] = [underlying_ggal, underlying_cepu];

const maturities: Maturity[] = [
  {
    date: '2022-10-21T03:00:00.000Z',
    label: '21/10/2022',
  },
  {
    date: '2022-12-16T03:00:00.000Z',
  },
  {
    date: '2023-02-17T03:00:00.000Z',
    label: '17/2/2023',
    daysToExpiration: 122,
  },
];

const market_data_ggal: MarketData = {
  seqNumber: 514625346154236512,
  id: 'bm_MERV_GGAL_48hs',
  bidSize: 10.1,
  bidPrice: 15.5,
  askSize: 5,
  askPrice: 18.26,
  lastPrice: 3.1,
  change: -2.1845,
  volume: 2000,
  effectiveVolume: 2500,
  settlementOrClosePrice: 16.5,
  impliedVolatility: 7.5,
  lastPriceDateTime: '2022-02-11T03:00:00.000Z',
  bidSizeStr: '10,1',
  bidPriceStr: '15,5',
  askSizeStr: '5',
  askPriceStr: '18,26',
  lastPriceStr: '3,1',
  changeStr: '-2,18',
  volumeStr: '2.000',
  effectiveVolumeStr: '2.500',
  settlementOrClosePriceStr: '16,5',
  impliedVolatilityStr: '7,5',
};

const context_data: ContextData = {
  volatility: 40,
  riskFreeRate: 70.5,
  maturityMonthYearList: maturities,
};

export {
  options_ggal_202210,
  options_cepu_202210,
  underlying_ggal,
  underlying_cepu,
  underlyings,
  maturities,
  market_data_ggal,
  context_data
};
